name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10","3.11","3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint

    - name: Install dependency from source
      run: |
        pip install git+https://github.com/deepmodeling/dpgen2.git  # Replace with the actual repository

    - name: Install project dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .  # Install dependencies from setup.py
        
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
