name: Release
on:
  push:
    branches:
      - main
      - devel

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        persist-credentials: false # <--- this

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: pip install python-semantic-release

    - name: Run semantic-release
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        GIT_COMMIT_AUTHOR: ${{ vars.GIT_COMMIT_AUTHOR }}
      run: semantic-release  version 